joints:
  - name: front_left
    type: motor
    params:
      attachment: 0
      rc_addy: 129
      m1: yes
      ticks_per_rev: 6533
  - name: front_right
    type: motor
    params:
      attachment: 0
      rc_addy: 129
      m1: no
      ticks_per_rev: 6533
  - name: back_left
    type: motor
    params:
      attachment: 0
      rc_addy: 130
      m1: yes
      ticks_per_rev: 6533
  - name: back_right
    type: motor
    params:
      attachment: 0
      rc_addy: 130
      m1: no
      ticks_per_rev: 6533
  - name: bridge_release
    type: servo
    params:
      attachment: 2
      servo_port: 0
      PCA_address: 0x40
      maximum_value: 0xFFFF
      minimum_value: 0x0000
      


