grr/robot:
  ros__parameters:
    pca_address: 0x40
    pca_frequency: 100
    servo_mapping:
      bridge_latch_joint:
        port: 15
        maximum: 4850
        minimum: 3500
      mechanism_lift_joint:
        port: 14
        maximum: 0
        minimum: 0
      mechanism_package_joint:
        port: 13
        maximum: 11316
        minimum: 6880
      mechanism_thruster_joint:
        port: 12
        maximum: 11500
        minimum: 3000
      small_package_sweeper_joint:
        port: 11
        maximum: 0
        minimum: 0