name: Ros2 Build
on:
    - push
    - pull_request

jobs:
    test:
        runs-on: ubuntu-latest 
        steps:
            - uses: actions/checkout@v2
            - name: build docker container
              run: docker buildx build -t local Dockerfile
              working-directory: Robot2023/
            - name: colcon build
              run: docker run -it local colcon build