name: Ros2 Build
on:
    - push
    - pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        container: ros:humble-ros-core-jammy
        steps:
            - uses: actions/checkout@v2
            - name: build
              run: colcon build